### PR TITLE
Add auth

### PR DESCRIPTION
**Pull request by BlazingAura**

### CODE REVIEW

**Comment by CreaturePhil** [comment]
Double for loops are slow, can you make it into one loop? Also can you require lodash and use its forIn https://lodash.com/docs#forIn Use `hashColor` as well for the names.

**Comment by BlazingAura** [comment]
sure

**Comment by CreaturePhil** [comment]
@BlazingAura cool, can you rebase?

**Comment by BlazingAura** [comment]
about that .......

**Pull request closed without merging**
