### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by jaredgrady**

### CODE REVIEW

**Comment by CreaturePhil** [comment]
Why a `gif`? Wouldn't a `png` or `jpg` be more efficient?

**Comment by jaredgrady** [comment]
It was the format it was delivered to me in. I can convert it although idk if its gonna be lossless.

**Comment by CreaturePhil** [comment]
@TheFenderStory google gif to png or gif to jpg xaa

**Comment by jaredgrady** [comment]
LOL its easy enough to convert.

**Comment by CreaturePhil** [comment]
@TheFenderStory After looking at it in the navbar of the app, the logo isn't really that good. Also the background of the logo is not transparent.

gryph logo

**Pull request merged**
